In [61]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [63]:
dataset = pd.read_csv('insurance_pre.csv')

In [65]:
dataset

,age,sex,bmi,children,smoker,charges
0,19,female,27.900,0,yes,16884.92400
1,18,male,33.770,1,no,1725.55230
2,28,male,33.000,3,no,4449.46200
3,33,male,22.705,0,no,21984.47061
4,32,male,28.880,0,no,3866.85520
...,...,...,...,...,...,...
1333,50,male,30.970,3,no,10600.54830
1334,18,female,31.920,0,no,2205.98080
1335,18,female,36.850,0,no,1629.83350
1336,21,female,25.800,0,no,2007.94500


In [67]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [69]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [71]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [73]:
independent

,age,bmi,children,sex_male,smoker_yes
0,19,27.900,0,False,True
1,18,33.770,1,True,False
2,28,33.000,3,True,False
3,33,22.705,0,True,False
4,32,28.880,0,True,False
...,...,...,...,...,...
1333,50,30.970,3,True,False
1334,18,31.920,0,False,False
1335,18,36.850,0,False,False
1336,21,25.800,0,False,False


In [75]:
dependent

,charges
0,16884.92400
1,1725.55230
2,4449.46200
3,21984.47061
4,3866.85520
...,...
1333,10600.54830
1334,2205.98080
1335,1629.83350
1336,2007.94500


In [77]:
#split into training set and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [79]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train) #fit=calculation and transform peform calculation and provide results
x_test=sc.transform(x_test)

In [81]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)


In [83]:
x_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [85]:
y_train

array([[-9.74704706e-01],
       [ 2.43595227e+00],
       [-3.54990167e-01],
       [-7.40302357e-01],
       [-7.72992119e-01],
       [-3.56105745e-01],
       [-3.12405716e-01],
       [-4.57593414e-01],
       [-1.32221217e-01],
       [-7.93946645e-01],
       [-9.29662595e-01],
       [-8.53316663e-01],
       [-7.77169102e-01],
       [-4.74957055e-01],
       [ 1.80292292e+00],
       [-1.77344443e-02],
       [-5.06614701e-01],
       [ 1.10861258e+00],
       [-1.18018584e-01],
       [-9.62233850e-01],
       [-1.95774021e-01],
       [-1.98220356e-01],
       [-7.48375214e-01],
       [-9.73871211e-01],
       [ 2.62922835e+00],
       [-4.66763102e-01],
       [ 1.28665821e+00],
       [-8.07799710e-01],
       [ 9.62739634e-01],
       [-6.47487283e-01],
       [-1.09681055e-01],
       [ 3.90197468e-01],
       [ 1.75728577e+00],
       [-3.02271094e-01],
       [-4.33454326e-01],
       [-9.67185594e-01],
       [-7.53146992e-01],
       [-4.09292284e-01],
       [-9.3

In [87]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf',C=10)

In [89]:
regressor.fit(x_train,y_train)

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=10)

In [91]:
y_pred=regressor.predict(x_test)

In [93]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [95]:
r_score

0.8818140952905176

In [97]:
import pickle
filenm="final_model_svm.sav"

In [99]:
pickle.dump(regressor,open(filenm,'wb'))

In [101]:
filesc="sdsc.sav"

In [103]:
pickle.dump(sc,open(filesc,'wb'))

In [105]:
filescy="sdscy.sav"

In [107]:
pickle.dump(scy,open(filescy,'wb'))

In [109]:
preip=sc.transform([[19, 1, 27.9, 0, 0]])

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [111]:
preip

array([[-1.46814257, -4.80180845, 22.31352362, -0.98885138, -0.49929923]])

In [113]:
lo_model=pickle.load(open("final_model_svm.sav",'rb'))
result=lo_model.predict(preip)

In [115]:
result

array([0.56096722])

In [117]:
preop=scy.inverse_transform([result])

In [119]:
preop

array([[19766.15063907]])